### ISSUE TITLE
Actividad 1: Mapa mental

### ISSUE THREAD

**Issue by SANDRAVELASCO** [SistemasTecTlaxiaco/actividad-1-mapa-mental-SANDRAVELASCO#1]
[Mapa mental Ingeniería de requerimientos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-SANDRAVELASCO/files/10610140/Mapa.mental.Ingenieria.de.requerimientos.pdf)

**Comment by mel-16** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
